### ISSUE TITLE
React Native Project Import Image @1x, @2x, @3x

### ISSUE THREAD

**Issue by jigs611989** [benawad/destiny#115] opened 2020-04-24 16:07 UTC
`$ destiny ./src `

INFO: Generating tree for: ./src
ERROR: Cannot find import ./Img/sam.png

Actually, the files are sam@1x.png, sam@2x.png, sam@3x.png but we just have to use it as 
require('./Img/sam.png')

For Example
```
.
├── button.js
└── img
    ├── check.png
    ├── check@2x.png
    └── check@3x.png

```

`
<Image source={require('./img/check.png')} />
`

For detail check [Images - React Native](https://reactnative.dev/docs/images)

**Comment by AnatoleLucet** [comment] 2020-04-24 16:25
duplicate of #107

**Comment by AnatoleLucet** [comment] 2020-07-03 18:27
It seems like the author of #107 has changed the purpose of the issue, so I'll reopen this one.

**Closed** 2020-08-19 15:10 UTC
Labels: enhancement
