### ISSUE TITLE
reserved paths

### ISSUE THREAD

**Issue by jesperordrup** [benawad/destiny#82] opened 2020-02-27 16:20 UTC
So I tried destiny on a next.js project and realized that we need to have some way to exclude folders/files.

Example, in next.js we need to keep code for pages and api in 

pages
pages/api

**Comment by benawad** [comment] 2020-02-27 16:28
For now, you can accomplish that with your glob `./!(pages|server)*`, but I could see adding a more friendly api to `destiny` for excluding files

**Comment by sQVe** [comment] 2020-02-27 17:04
Duplicate of https://github.com/benawad/destiny/issues/17. Closing.

**Closed** 2020-02-27 17:04 UTC

**Comment by danielpza** [comment] 2020-02-27 17:09
I think it would be better to have that big issue separated in small ones like this, it allows to discuss different issues without spamming or polluting the others. If we want to track them all in a single place it would be better to use github projects.

**Comment by sQVe** [comment] 2020-02-27 17:27
@danielpza I agree, I had the exact same though. We should close #17 and split the relevant points in it into separate issues.

**Comment by jesperordrup** [comment] 2020-02-27 19:06
> For now, you can accomplish that with your glob `./!(pages|server)*`, but I could see adding a more friendly api to `destiny` for excluding files

I feel a need for a `.destiny` file

**Comment by sQVe** [comment] 2020-02-27 19:10
> I feel a need for a `.destiny` file

@jesperordrup `destiny` already supports a config file via https://github.com/davidtheclark/cosmiconfig but it does not currently support specifying paths in it.

**Comment by AnatoleLucet** [comment] 2020-02-27 19:14
I feel a need for a **Documentation** 😄 

---

Going to work on it...

**Comment by jesperordrup** [comment] 2020-02-27 20:57
> For now, you can accomplish that with your glob `./!(pages|server)*`, but I could see adding a more friendly api to `destiny` for excluding files

This will exclude the files. Which leads to a new problem. You only want to exclude them from being relocated. You still want them to be updated with new paths to all the referenced files that are moved around.

**Comment by AnatoleLucet** [comment] 2020-02-27 21:06
@jesperordrup #70 ?
